name: test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang-format clang-tidy
          version: 1.0

      - name: Set up Python environment
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: "3.13"
          working-directory: firmware

      - name: Run check target
        run: make check

  firmware-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python environment
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: "3.13"
          working-directory: firmware

      - name: Create config.h from example
        working-directory: firmware
        run: |
          if [ ! -f include/config.h ]; then
            cp include/config.h.example include/config.h
            echo "Created config.h from example"
          fi

      - name: Test firmware
        working-directory: firmware
        run: make test

      - name: "Upload coverage data"
        uses: actions/upload-artifact@v5
        with:
          name: firmware-coverage
          path: firmware/.pio/build/native
          if-no-files-found: ignore
          include-hidden-files: true

  firmware-coverage:
    runs-on: ubuntu-latest
    needs: firmware-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: lcov
          version: 1.0

      - name: Set up Python environment
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: "3.13"
          working-directory: firmware

      - name: Download coverage data
        uses: actions/download-artifact@v6
        with:
          path: firmware

      - name: Run coverage target
        working-directory: firmware
        run: make coverage

      - name: Upload HTML report if check failed.
        uses: actions/upload-artifact@v4
        with:
          name: firmware-report
          path: firmware
        if: ${{ failure() }}
